### A zoo of matrices

In [2]:
import numpy as np

In [23]:
Square      = np.random.randn(5, 5)
Rectangular = np.random.randn(5, 2)

print(Square, Rectangular, sep='\n\n')

[[-0.62159978  0.3792484   0.32303348  0.07488851 -2.78427871]
 [ 0.97891135 -0.39787205 -0.48633442 -0.40876008  3.18915808]
 [-2.14963016  1.39204898 -0.73699978 -0.55064547  0.69770615]
 [ 0.73168347 -1.31123024  1.33661571 -0.69887327 -0.99149088]
 [ 0.38228314 -1.5311615   0.52074445 -1.41209392 -0.40111368]]

[[ 0.19606443  0.53746371]
 [-0.73223529 -0.37096323]
 [-1.01471095  0.61494459]
 [-0.75961861  0.87082403]
 [-0.93316271 -0.17018335]]


In [21]:
# identity

I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# zeros

Z = np.zeros((4, 4), dtype=int)
print(Z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [33]:
# diagnonal

D = np.diag([1,2,3,4,5])
print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [36]:
# triangular

S = np.random.randn(3, 3)

U = np.triu(S)
L = np.tril(S)

print(U, L, sep='\n\n')

[[-0.18625736  0.87821295 -1.64473085]
 [ 0.          0.34718482 -0.41657951]
 [ 0.          0.         -0.70478713]]

[[-0.18625736  0.          0.        ]
 [-0.58369491  0.34718482  0.        ]
 [-0.29178159 -0.53794317 -0.70478713]]


In [40]:
# concatenate matrices

A = np.random.randn(4, 2)
B = np.random.randn(4, 4)

C = np.concatenate((A, B), axis=1)

print(C)

[[-0.33680865 -0.13890477 -0.53600618 -0.19114338 -0.59570909 -1.37168435]
 [-0.39627804  1.16617517  0.58733709 -0.67048958  0.24185779  0.47771485]
 [ 1.34224908 -0.93424105  0.20720806 -1.17667463 -0.23015412 -0.6394361 ]
 [-1.43943284 -0.72963022  0.11698272  1.02349358 -0.26398716 -0.15255042]]


In [42]:
A = np.random.randn(3, 4)
B = np.random.randn(4, 4)

C = np.concatenate((A, B), axis=0)

print(C)

[[-0.29218466 -0.89028888 -0.94417298  0.10544818]
 [ 2.33335567  1.61649351  0.10195513 -1.20155761]
 [ 0.8257232   0.56522495  0.11397813 -1.91802663]
 [-0.77245935 -0.03447898  1.40281537  0.26553544]
 [-0.63376532  0.08724588  1.2745596  -0.44027889]
 [-0.95348089 -0.41190279  0.46532172  1.0456932 ]
 [ 0.79083569  2.20363943  1.04104777  0.22786232]]


###  Matrix + and - (element wise)

In [51]:
# same dim

A = np.random.randn(3, 4)
B = np.random.randn(3, 3)
C = np.random.randn(3, 4)

try:
    print(A + B)
except ValueError as e:
    print(e)
print('\n')
print(C + A)

operands could not be broadcast together with shapes (3,4) (3,3) 


[[ 0.43930996  1.02031349  3.282331    0.60891312]
 [-0.14345149 -0.92910097 -0.84878237  0.00831106]
 [-1.34086932 -1.86409315  0.31354025  0.08030837]]


In [64]:
# "shifting" a matrix (square only)
N = 3

A = np.random.randn(N, N)
I = np.eye(N)            # same N dim
lambda_ = 99999901

print(A)
print('\n')
print(A+lambda_*I)       # A + lambda*I = C

[[ 1.32058872  0.23264834  1.03944976]
 [ 0.590518    0.38501706 -0.26374421]
 [-1.14813628 -1.2009648   0.34774629]]


[[ 9.99999023e+07  2.32648342e-01  1.03944976e+00]
 [ 5.90518003e-01  9.99999014e+07 -2.63744211e-01]
 [-1.14813628e+00 -1.20096480e+00  9.99999013e+07]]


### Matrix * (element wise)

In [67]:
M = np.array([ [1,2], [2,5] ])
s = 2

print(M*s)
print('\n')
print(s*M)

[[ 2  4]
 [ 4 10]]


[[ 2  4]
 [ 4 10]]


In [80]:
# test for s(A+B) = sA + sB

M = 3
N = 2

A = np.random.randn(M, N)
B = np.random.randn(M, N)
s = 88

print(
    s*(A+B),
    s*A + s*B,
    
    np.sum(s*(A+B)),
    np.sum(s*A + s*B),
    
    np.sum(s*(A+B)) - np.sum(s*A + s*B),
    
    sep='\n\n',
    )

[[ 132.85349803   87.58156567]
 [ -84.24873504  270.02524468]
 [ -36.83126425 -214.53693882]]

[[ 132.85349803   87.58156567]
 [ -84.24873504  270.02524468]
 [ -36.83126425 -214.53693882]]

154.84337026855985

154.8433702685599

-5.684341886080802e-14


### Transpose

In [85]:
M = np.array([[1,2,3],
              [2,3,4]])

print(M, end='\n\n')
print(M.T, end='\n\n')
print(M.T.T, end='\n\n')

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]



In [86]:
np.transpose([[1,2,3],
              [2,3,4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [88]:
C = np.array([ [4+1j, 3, 2-4j] ])

print(C)
print('\n')
print(C.T)

[[4.+1.j 3.+0.j 2.-4.j]]


[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]


In [92]:
# Hermitian transpose

print(np.matrix(C).H)

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]


### Diagonal and Trace

In [99]:
# get integers from randn
M = np.round(5*np.random.randn(5, 5))

d = np.diagonal(M)
d = M.diagonal()

print(M)
print('\n')
print(d)

[[-1.  5. 11. -4.  0.]
 [-3. -2. -1.  6. -7.]
 [-2. -7.  2.  4.  7.]
 [-6. -7. -2.  4. -7.]
 [ 0.  0. -0. -8. -1.]]


[-1. -2.  2.  4. -1.]


In [100]:
tr = M.trace()
tr = np.trace(M)
tr = np.sum(M.diagonal())

print(tr)

2.0


### Linearity of Trace

In [103]:
# tr(A)+tr(B) ?= tr(A+B)
tr = np.trace

A = np.round(5*np.random.randn(5, 5))
B = np.round(5*np.random.randn(5, 5))

tr(A)+tr(B), tr(A+B)

(-4.0, -4.0)

In [104]:
# tr(1*A) ?= 1*tr(A)

tr(1*A), 1*tr(A)

(-7.0, -7.0)

### Matrix Broadcosting

In [105]:
np.reshape(range(1, 13), (3, 4), 'C')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
np.reshape(range(1, 13), (3, 4), 'F')

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [110]:
A = np.reshape(range(1, 13), (3, 4), 'F')

r = [10, 20, 30, 40]
c = [100, 200, 300]

In [111]:
# broadcost on the rows

print(A+r)

[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]


In [113]:
# broadcost on the cols

print(A+np.matrix(c).T)

[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]


In [119]:
print(A+np.reshape(c, (len(c), 1)))

[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
